### ISSUE TITLE
How do you handle list styles when using `ul[class], ol[class]` in the reset?

### ISSUE THREAD

**Issue by paulshryock** [Andy-set-studio/modern-css-reset#18]
Re: `ul[class], ol[class]` from #10

> The beauty of this reset is that it's so tiny, taking elements away that are causing problems is really easy. A few people don’t like the `ul[class], ol[class]` stuff and my response to them each time is basically “don't use them, then”.
-- https://github.com/hankchizljaw/modern-css-reset/pull/10#issuecomment-540979032

@hankchizljaw, I noticed when including `ul[class], ol[class]` (which I love in theory), that if I give a list a class name like `.list`, its styles are still overridden by `ul[class]`, which has higher specificity. So to override the reset, I'd need to use a selector like `ul.list`. Is this intentional, or how do you handle list styles when using `ul[class], ol[class]` in the reset?

I get that I could simply "don't use them, then", which is a perfectly suitable solution. But I'm interested to hear what your approach to styling lists is, with this reset. Thanks!

**Comment by Andy-set-studio** [comment]
It's pretty straightforward: if a list is to be a list, then I style the semantic element directly: 

```css
.my-component ul {
  ...
}
```

**Comment by paulshryock** [comment]
Gotcha. Thanks for clarifying.
