### ISSUE TITLE
li { margin: 0; }

### ISSUE THREAD

**Issue by jbcaprell** [Andy-set-studio/modern-css-reset#19]
Caveat: I only mention this because of the [code golf-y](https://hankchizljaw.com/wrote/a-modern-css-reset/#heading-a-reset-of-sensible-defaults) nature of your reset.

I’m not actually aware of any user agent, [Blink](https://chromium.googlesource.com/chromium/blink/+/master/Source/core/css/html.css), [Gecko/Quantum](https://dxr.mozilla.org/mozilla-central/source/layout/style/res/html.css), [WebKit](https://trac.webkit.org/browser/trunk/Source/WebCore/css/html.css), or [EdgeHTML](https://gist.github.com/jonathantneal/abc52743caa0a019d359ec4ba2ce965b) (whose stylesheet is, technically, closed-source, whatever sense that makes) that applies a margin to `li` elements, and so this line *may* be unnecessary:

https://github.com/hankchizljaw/modern-css-reset/blob/12e77f9a895255554e339b3de2c09b12f085dea3/src/reset.css#L23

**Comment by jbcaprell** [comment]
(This is also true of `figcaption`, I think)

https://github.com/hankchizljaw/modern-css-reset/blob/12e77f9a895255554e339b3de2c09b12f085dea3/src/reset.css#L25

**Comment by Andy-set-studio** [comment]
PR 100% welcome for this :)
