### ISSUE TITLE
Question about the `min-height: 100vh;`

### ISSUE THREAD

**Issue by CyrilKrylatov** [Andy-set-studio/modern-css-reset#4]
Hi Andy,

Your modern CSS Reset is awesome. We needed a new approach on the whole reset thing and you did a great job.

Anyway I may have an issue / question about the `min-height: 100vh;` you [put on the body element](https://github.com/hankchizljaw/modern-css-reset/blob/master/src/reset.css#L33-L34).

I was reading a few days ago [this article](https://chanind.github.io/javascript/2019/09/28/avoid-100vh-on-mobile-web.html) that we should not use this on mobile because of address bar and all. [Here](https://nicolas-hoizey.com/2015/02/viewport-height-is-taller-than-the-visible-part-of-the-document-in-some-mobile-browsers.html) you have an other article about that too.

That's not an issue per say, I'm curious on your thoughts about this subject.

Thank you for your time.

Cheers! ✌️

**Comment by Andy-set-studio** [comment]
Howdy! 

I put this rule in because the probability that your body will be shorter than the viewport is pretty minuscule. I guess if your thing is going to be the exact height of the viewport, remove the rule from the reset 👍
