### ISSUE TITLE
prefers-reduced-motion transition styles can break JS

### ISSUE THREAD

**Issue by atomiks** [Andy-set-studio/modern-css-reset#5]
From [this comment](https://www.reddit.com/r/webdev/comments/dc9vkv/a_modern_css_reset_andy_bell/f28bydo?utm_source=share&utm_medium=web2x)

> The reduced motion CSS will break any functionality relying on the JS “transitionend” event.
>
> https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/transitionend_event
>
> If there is no transition delay or duration, if both are 0s or neither is declared, there is no transition, and none of the transition events are fired.

I think a tiny value like `1ms` instead of `0s` can fix this.

**Comment by Andy-set-studio** [comment]
Interesting stuff! Happy to take a PR!
