### ISSUE TITLE
Adding padding-inline-start: 0px;

### ISSUE THREAD

**Issue by BenTechCoder** [Andy-set-studio/modern-css-reset#53]
Hey everyone! So, I've been using this CSS reset on some client and personal projects and I've noticed that my layouts constantly get out of shape because of user agent styling on Microsoft Edge (haven't tested this on any other browser). This user agent styling applies a padding-inline-start of 40px. I was constantly being bamboozled by this issue and it would be helpful to add 

`padding-inline-start: 0px;`

to somewhere in the reset

Let me know what you think! 

Best,
Benjamin Lebron

**Comment by Andy-set-studio** [comment]
Is that padding applied to lists? I'm actually a fan of the default padding on lists tbh

**Comment by BenTechCoder** [comment]
It is in microsoft edge and becuase its set in pixels it often mis-aligns my layouts on mobile

**Comment by BenTechCoder** [comment]
Let me share a screenshot real quick

![image](https://user-images.githubusercontent.com/71533854/140781331-17b209cd-9d23-4e53-871a-83b4798d3658.png)


Before I reset inline-padding

![image](https://user-images.githubusercontent.com/71533854/140781133-3655c6e8-04ac-4146-a5de-dde966c4eae4.png)
After I reset the padding-inline-start

**Comment by BenTechCoder** [comment]
If you approve, I can submit a pull-request adding this in for Microsoft-edge but I also believe Safari and Firefox does this as well

**Comment by Andy-set-studio** [comment]
So are these elements in a list then? Not really too hot on the idea of user-agent specific stuff in this reset if I'm honest

**Comment by BenTechCoder** [comment]
Here's my code:

```
<li>
<article class="snippet">
<img src="{{ guides.data.image }}" alt="{{ guides.data.title }}" class="snippet_image">
<h3 class="snippet_title">{{ guides.data.title }}</h3>
<p class="snippet_body">{{ guides.data.description }}</p>
<p class="snippet_body"> Last updated <span>{{ guides.data.date }}</span></p>
<div class='btn-container'><a href="{{ guides.url }}" class="btn btn--primary">Continue Reading</a></div>
</article>
</li>

```
Here the issue is that the entire list item is pushed to the right therefore reseting the inline start would allow people to choose their own padding

**Comment by BenTechCoder** [comment]
Although I might be in error because I set my own padding to this element and the user-agent still added in the 40px. Also there is already a reset in padding in the reset but for some reason it does not annul the inline-start

**Comment by Andy-set-studio** [comment]
Hmmm yeh it sounds to me like there could be an issue there local to your project. I'll close this for now, but I hope you find the resolution to it!

**Comment by BenTechCoder** [comment]
Ok cool, I'll do my best to debug. Maybe it's because I'm on an older version of MS Edge? I just updated though so maybe not? I'm still very inexperienced so as I progress in my coding journey I suppose It'll be fixed. Thanks for your time Andy! And your amazing content on your blog (you have no idea how it's helped me).

Best,
Ben

**Comment by Andy-set-studio** [comment]
Thanks, Ben. That's great to hear!
